name: push-main
run-name: ${{ github.actor }} deploys on push to ${{GITHUB_REF##*/}}
on:
  push:
    branches:
      - 'main'
      - '23-feed-update-routes'
jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
