name: deploy-prod
run-name: ${{ github.actor }} deploys on push to ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - '70-fix-months-is-an-invalid-keyword-argument-for-__new__'
jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
