name: main-push
run-name: ${{ github.actor }} deploys on push to main
on:
  push:
    branches:
      - 'main'
      - '18-raise-error-when-no-rss-links-provided'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
