name: schedule-data-parsing
run-name: ${{ github.actor }} starts scheduled data parsing
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  data_parsing:
    runs-on: self-hosted
    steps:
      - name: Send request
        run: STATUS_CODE=`curl --write-out '%{http_code}' --silent --output /dev/null -X PUT "http://192.168.0.155:30010/feeds/parse/runner"`
      - name: Parser runner status checker
        if: ${{ STATUS_CODE }} != 200
        uses: actions/github-script@v3
        run: core.setFailed('Status ${{ STATUS_CODE }} returned != 200')
