name: schedule-data-parsing
run-name: ${{ github.actor }} starts scheduled data parsing
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  data_parsing:
    runs-on: self-hosted
    steps:
      - name: Send request
        run: curl -X PUT "http://192.168.0.155:30010/feeds/parse/runner"
