name: schedule-healthcheck
run-name: Scheduled healthcheck
on:
  push:
    branches:
      - '85-testing-healthcheck'
#   schedule:
#     - cron: '* * * * *'
jobs:
  data_parsing:
    runs-on: self-hosted
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: http://127.0.0.1:30010/healthcheck/
      - name: Send request and save response
        run: echo "is_healthy=`curl --silent GET 'http://127.0.0.1:30010/healthcheck/'`" >> "$GITHUB_ENV"
      - name: Print status
        run: echo "$is_healthy"
      - name: Check health status
        run: if ([[ "$is_healthy" == "true" ]]); then exit 0; else echo "$is_healthy"; exit 1; fi
