name: scheduled-healthcheck
run-name: Scheduled healthcheck
on:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  data_parsing:
    runs-on: self-hosted
    steps:
      - name: Send request and save response
        run: echo "is_healthy=`curl --silent GET 'http://192.168.0.155:30010/healthcheck/'`" >> "$GITHUB_ENV"
      - name: Print status
        run: echo "$is_healthy"
      - name: Check health status
        run: if ([[ "$is_healthy" == "true" ]]); then exit 0; else echo "$is_healthy"; exit 1; fi
